server:
  port: 9000

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres!
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true




auth:
  provider-uri: https://localhost:9000
